---
abstract: 'convenience methods for using Data::ICal with DateTime'
author:
  - 'Simon Wistow <simon@thegestalt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::LongString: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-ICal-DateTime
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Accessor: 0
  Clone: 0
  Data::ICal: '0.07'
  DateTime::Format::ICal: 0
  DateTime::Set: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.8'
